### ISSUE TITLE
Animation editor UI - Menu layer should always be on top.

### ISSUE THREAD

**Issue by lim147** [lix229/UnityRuntimeImport#1]
When the cube size is getting larger and it covers the "Pause" button, I could not click on the "Pause" button to end the animation immediately and I have to wait until the cube size is getting smaller. Maybe change the layer order of cube and button so that the Pause button can be pressed anytime immediately after the animation starts.

<img width="1151" alt="Screen Shot 2021-02-25 at 1 59 58 PM" src="https://user-images.githubusercontent.com/35234798/109203350-0c397000-7772-11eb-8890-93c0bd374ffd.png">

**Comment by zhouh46** [comment]
Thanks for the feedback!
Due to the way of our implementation, the animation was done through CSS, which can block some buttons and text boxes while the object was big enough and takes up the whole screen. We are considering bringing the menu to the front which solves this issues but it may block a portion of the object when it is so big.

**Comment by lix229** [comment]
This is now fixed.
