### ISSUE TITLE
AnimationObj.animCtrl is never assigned to

### ISSUE THREAD

**Issue by Gabriel-Gebril** [lix229/UnityRuntimeImport#25]
Assets\Scripts\AnimationObj.cs(8,22): warning CS0649: Field 'AnimationObj.animCtrl' is never assigned to, and will always have its default value null

**Comment by lix229** [comment]
In my own experience with this module, 

- This warning does not affect the actual functionality
- The end user should not see it since we are aiming to implement a solution without needing the end user to use Unity Editor.
- Let me know if this does raise any error, if so please also attach the version of Unity you're running, and how to recreate the issue.

Thank you for the feedback! :)
