### ISSUE TITLE
Animation Editor - Multiple Rotations within 1 Frame

### ISSUE THREAD

**Issue by raziusyed** [lix229/UnityRuntimeImport#50]
### Description:
I've noticed multiple rotations of the cube when playing my animation in which I've only added 1 frame. This does not seem right.

### Environment:
Device: Macbook Pro 2015
Browser: Chrome

### Steps to Reproduce:
1. Open the Animation Editor 
2. Set frametime to `500` ms
3. Set `z` value to `1`
4. Set `deg` to `90`
5. Set remaining rotation values to 0
6. Set Scale values to 1
7. Set Translate values to 0
8. Click Play

### Actual Result:

Can see that a 90 degree rotation has already been completed at 231.9ms:

![image](https://user-images.githubusercontent.com/25377291/110254373-eaec3700-7f5c-11eb-9c0a-a1d5d34a89ae.png)

### Expected Result:

I would expected that the rotations would be performed over the length of time between frames, however it looks like multiple rotations are occuring between frames

### Severity: Medium

**Comment by lix229** [comment]
This seems to be a bug with the slider rather than the animation rendering, if I export the animation with this setting, the values are correct.

As the slider is updating the frametime textboxes, it messes up the frametime when asynchronousation happens, which will happen due to the way JS handles time passed by.

Thus the slider will be replaced with something else.
