### ISSUE TITLE
Animation editor - fast translations are very choppy at higher speeds

### ISSUE THREAD

**Issue by Erikkre** [lix229/UnityRuntimeImport#59]
### Description:
Not when rotating or scaling, but translating quickly, one can see the individual frame skips that the cube does as it moves

### Environment:
Device: Windows 10 gaming desktop
Browser: Chrome

### Steps to Reproduce:
Open the Animation Editor
Put in a frame time such as 1000ms and translation such as 10000, 0, 0
press play

### Actual Result:
The cube does not move smoothly and quickly out of view, but possibly because of the low browser fps, appears choppy and can be seen "skipping through the frames" as it moves out of view (it appears as though there are 5 cubes as it moves across the screen, as there is not a high enough framerate to produce translations as you would expect them to appear at anything faster than medium speed)

### Expected Result:
The cube should fluidly move during a translation

**Comment by lix229** [comment]
This is the expected behavior due to limitations of animations being rendered.

If the frametime is too small for the transitions, i.e. fps needed or being rendered is greater than number of frames being refreshed per second on your monitor, there will be "choppyness".

This is a bit like why vertical synchronization is needed sometimes.
