### ISSUE TITLE
Animation Editor - inconsistent placeholder values for inputs

### ISSUE THREAD

**Issue by Erikkre** [lix229/UnityRuntimeImport#63]
### Description:
When adding a keyframe, if only 1 value is inputted for one of the settings i.e. translation, an error is returned saying that a keyframe must have at least 1 transformation, while the other settings not partly filled in i.e. rotation and scale, have default values for their unfilled boxes

### Environment:
Device: Windows 10 gaming desktop
Browser: Chrome

### Steps to Reproduce:
Open the Animation Editor
Put in any frametime, and for the settings, fill any one axes of any one setting and leave the rest blank
add keyframe

### Actual Result:
Here is the error popping up, when the blank translation values should be their default values 0 and 0, just like for rotation and scaling (scaling's default values are 1, 1, 1):
![image](https://user-images.githubusercontent.com/29803319/110269392-92835c80-7f91-11eb-92d4-aa54b5cb52fc.png)

### Expected Result:
Consistency is key for user experience and expectations- if the other settings i.e. rotation are defaulted to 0 with no input, and scaling is defaulted to 1 with no input, then the rest of i.e. translate should default to 0 when only one of the axes are filled.

**Comment by lix229** [comment]
This is because if not all fields are filled in, the input is deemed invalid, thus the renderer does not see any input at all.

We considered adding default values if fields for a transition are partially filled, but the rational behind leaving fields blank are up to debate, i.e. should values from previous frames be filled in? or should just fill in 1 or 0 instead?

Thus we chose to enforce input being fully filled in.

Will change the prompt message though, good point.

**Comment by lix229** [comment]
This is now fixed.
