### ISSUE TITLE
Changing animation name from "default" in SampleAnim

### ISSUE THREAD

**Issue by teemh** [lix229/UnityRuntimeImport#9]
Sort of confused. According to your documentation shouldn't this work? Cube doesn't move though.

Test,1,NA
1,Obj,Test,0,0,0,0,0,0,0,0,0,1,1,1
1,Test,1000,0,0,0,0,180,180,180,3,3,3
1,Test,2000,0,0,0,0,360,360,360,5,5,5
1,Test,3000,0,0,0,0,540,540,540,3,3,3
1,Test,4000,0,0,0,0,720,720,720,1,1,1

**Comment by lix229** [comment]
This is likely caused by not updating the properties of the object, specifically `animation`, `Obj` in this case.

Thus although the animation controller is trying to control animation `Test` attached to `Obj`, the `Obj` object does not have property `Test` attached, thus nothing could happen.

So this is expected.
